# Shell
command = /usr/bin/zsh

# Font
font-family = "PlemolJPConsole_NF"
font-style = Regular
font-size = 10

# Shell integration
shell-integration = detect
shell-integration-features = no-cursor,ssh-terminfo,ssh-env,title

# Window
scrollbar = system
split-inherit-working-directory = true

# Clipboard
copy-on-select = clipboard

# Mouse
mouse-scroll-multiplier = 4.95

# Scrollback
scrollback-limit = 100000
