[settings]
experimental = true
disable_backends = ["asdf", "vfox"]

[settings.pipx]
uvx = true

[tools]
# --- Runtimes ---
# Node.js
node = "24"
bun = "latest"
# Python
uv = "latest"
# --- Dev & VCS ---
gh = "latest"
lazygit = "latest"
neovim = "latest"
delta = "latest"
# --- Data & Search ---
jq = "latest"
ripgrep = "latest"
sqlite = "latest"
# --- Terminal UX & Shell ---
"github:rossmacarthur/sheldon" = "latest"
atuin = "latest"
bat = "latest"
chezmoi = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
starship = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
