alias eza="eza --icons=auto --git --group-directories-first"
alias ls="eza"
alias ll="eza -l"
alias la="eza -a"
alias lt="eza --tree"
alias lla="eza -la"
alias cat="bat --paging=never"

abbr -g "devnull"=">/dev/null 2>&1"
abbr -g "L"="| less"
abbr -g "xn"="| xargs nvim"

abbr "mkdir"="mkdir -p"

abbr "vi"="nvim"

abbr "g"="git"
abbr "gs"="git status"
abbr "gca"="git commit --amend"
abbr "gcim"="git commit -m"
abbr "gp"="git pull --rebase --autostash"
abbr "gpu"="git push"
abbr "gst"="git stash"
abbr "gstp"="git stash pop"
abbr "gsw"="git switch -c "
abbr "gre"="git rebase origin/main --autostash"
abbr "gres"="git restore ."
abbr "gsn"="git show --name-status"
abbr "gdn"="git diff --name-status origin/main"
abbr "t"="tig"
abbr "lg"="lazygit"